const artists = [
  {name:'Nilüfer Yanya',genre:'indie soul · london',mood:['Todo','Calma'],match:96,why:'Por tu gusto por voces íntimas, guitarras angulares y ritmos que respiran.',tone:'#7a665c',orb:'radial-gradient(circle at 35% 35%, #e0b9a7 0 13%, #936d67 14% 38%, #43383c 39% 62%, #171714 63%)'},
  {name:'Kelly Lee Owens',genre:'ambient techno · wales',mood:['Todo','Noche','Energía'],match:93,why:'El punto exacto entre tus playlists nocturnas y tu lado más electrónico.',tone:'#46525a',orb:'conic-gradient(from 30deg,#d9ff43,#7699a5,#20292d,#c5d0cf,#d9ff43)'},
  {name:'Mk.gee',genre:'alternative · new jersey',mood:['Todo','Calma','Noche'],match:91,why:'Texturas imperfectas y melodías cálidas que conectan con tus últimas escuchas.',tone:'#746955',orb:'radial-gradient(ellipse at 65% 35%,#efca77 0 8%,#997d50 9% 28%,#4a453d 29% 60%,#272421 61%)'},
  {name:'Ela Minus',genre:'indietrónica · bogotá',mood:['Todo','Energía','Noche'],match:89,why:'Sintetizadores humanos, pulsos hipnóticos y sensibilidad latina.',tone:'#674d51',orb:'conic-gradient(#ef6f75,#352e49,#bda7d9,#5b3542,#ef6f75)'},
  {name:'L’Rain',genre:'experimental pop · brooklyn',mood:['Todo','Calma'],match:87,why:'Capas vocales y curiosidad sonora para tu costado más explorador.',tone:'#556158',orb:'radial-gradient(circle at 50% 45%,#daf0bb 0 14%,#769678 15% 34%,#283832 35% 55%,#171714 56%)'},
  {name:'Overmono',genre:'electronic · uk',mood:['Todo','Energía'],match:85,why:'Percusión física y emoción contenida para subir la energía sin perder detalle.',tone:'#4e535e',orb:'conic-gradient(from 120deg,#97b7ff,#293653,#d0c3a7,#655c7d,#97b7ff)'}
];
let activeMood='Todo';
let saved=new Set(JSON.parse(localStorage.getItem('recomendapp-saved')||'[]'));
const grid=document.querySelector('#artistGrid');
const toast=document.querySelector('#toast');
const neighborStore=JSON.parse(localStorage.getItem('recomendapp-neighbors')||'{}');
let currentNeighborNames=[];
let compareMode='track',compareTracks=[];
let syncCancelled=false;

function render(){
  const list=artists.filter(a=>a.mood.includes(activeMood)).slice(0,3);
  grid.innerHTML=list.map((a,i)=>`<article class="artist-card" style="--tone:${a.tone};--orb:${a.orb};animation-delay:${i*.08}s">
    <span class="match">${a.match}% AFINIDAD</span><h3>${a.name}</h3><p>${a.why}</p><div class="card-bottom"><span class="genre">${a.genre}</span><button class="save ${saved.has(a.name)?'saved':''}" data-artist="${a.name}" aria-label="Guardar ${a.name}">${saved.has(a.name)?'✓':'＋'}</button></div></article>`).join('');
  document.querySelector('#savedCount').textContent=saved.size;
}
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
document.querySelectorAll('.mood').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.mood').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeMood=btn.dataset.mood;render()}));
grid.addEventListener('click',e=>{const btn=e.target.closest('.save');if(!btn)return;const name=btn.dataset.artist;saved.has(name)?saved.delete(name):saved.add(name);localStorage.setItem('recomendapp-saved',JSON.stringify([...saved]));render();notify(saved.has(name)?`${name} guardado en tu colección`:`${name} eliminado`)});
const api=window.musicAPI;
if(api)api.version().then(version=>document.querySelector('#appVersion').textContent=`v${version}`);
const dialog=document.querySelector('#settingsDialog');
async function loadConfig(){if(!api)return;const c=await api.getConfig();lastfmUser.value=c.lastfmUser;lastfmApiKey.value=c.lastfmApiKey;spotifyClientId.value=c.spotifyClientId;setConnected('Last.fm',!!(c.lastfmUser&&c.lastfmApiKey));setConnected('Spotify',c.spotifyConnected);if(c.lastfmUser&&c.lastfmApiKey)await loadRealRecommendations();}
function setConnected(service,on){const btn=[...document.querySelectorAll('.connect')].find(b=>b.dataset.service===service);btn.classList.toggle('connected',on);btn.querySelector('small').textContent=on?'Conectado':'Conectar';btn.querySelector('b').textContent=on?'✓':'+';}
async function loadRealRecommendations(){try{
  const top=await api.lastfm('user.getTopArtists',{period:'3month',limit:'8'});
  const lastfmSeeds=top.topartists.artist.slice(0,4);
  let spotifySeeds=[];
  try{const spotifyTop=await api.spotify('/me/top/artists?time_range=medium_term&limit=8');spotifySeeds=spotifyTop.items||[];}catch{}
  const seedNames=[...lastfmSeeds.map(a=>a.name),...spotifySeeds.map(a=>a.name)].filter((n,i,all)=>all.findIndex(x=>x.toLowerCase()===n.toLowerCase())===i).slice(0,6);
  const results=await Promise.all(seedNames.slice(0,4).map(name=>api.lastfm('artist.getSimilar',{artist:name,limit:'8',autocorrect:'1'})));
  const known=new Set(seedNames.map(name=>name.toLowerCase()));
  const found=results.flatMap(r=>r.similarartists?.artist||[]).filter(a=>!known.has(a.name.toLowerCase())).filter((a,i,all)=>all.findIndex(x=>x.name.toLowerCase()===a.name.toLowerCase())===i).slice(0,6);
  if(found.length){artists.splice(0,artists.length,...found.map((a,i)=>{const seed=seedNames[i%seedNames.length];const inSpotify=spotifySeeds.some(s=>s.name.toLowerCase()===seed.toLowerCase());return{name:a.name,genre:`similar a ${seed}`,mood:['Todo',i%2?'Noche':'Calma',i%3?'Energía':'Calma'],match:Math.max(78,96-i*3),why:`${inSpotify?'Spotify y Last.fm':'Last.fm'} lo conecta con ${seed}, parte central de tus escuchas.`,tone:['#7a665c','#46525a','#746955','#674d51','#556158','#4e535e'][i],orb:['radial-gradient(circle,#e0b9a7,#43383c 60%)','conic-gradient(#d9ff43,#7699a5,#20292d)','radial-gradient(circle,#efca77,#4a453d 60%)'][i%3]}}));render();notify(`Radar actualizado con Last.fm${spotifySeeds.length?' + Spotify':''}`);}
}catch(e){notify(e.message)} }
document.querySelectorAll('.connect').forEach(btn=>btn.addEventListener('click',async()=>{if(!api){notify('Abre la versión de escritorio para conectar cuentas');return;}if(btn.dataset.service==='Spotify'){try{notify('Abriendo autorización de Spotify…');await api.connectSpotify();setConnected('Spotify',true);notify('Spotify quedó vinculado');await loadRealRecommendations();}catch(e){notify(e.message)}}else dialog.showModal();}));
document.querySelector('#settingsBtn').addEventListener('click',async()=>{if(!api){notify('La configuración está disponible en la app instalada');return;}const c=await api.getConfig();lastfmUser.value=c.lastfmUser;lastfmApiKey.value=c.lastfmApiKey;spotifyClientId.value=c.spotifyClientId;dialog.showModal();});
document.querySelector('#settingsForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();await api.saveConfig({lastfmUser:lastfmUser.value.trim(),lastfmApiKey:lastfmApiKey.value.trim(),spotifyClientId:spotifyClientId.value.trim()});dialog.close();setConnected('Last.fm',!!(lastfmUser.value&&lastfmApiKey.value));notify('Configuración guardada en este equipo');await loadRealRecommendations();});
document.querySelector('#refreshBtn').addEventListener('click',()=>{artists.sort(()=>Math.random()-.5);render();notify('Tu radar se ha renovado')});
document.querySelector('#savedNav').addEventListener('click',()=>notify(saved.size?`Tienes ${saved.size} artista${saved.size===1?'':'s'} guardado${saved.size===1?'':'s'}`:'Aún no has guardado artistas'));

const neighborsView=document.querySelector('#neighborsView');
const compareView=document.querySelector('#compareView');
const discoverSections=[document.querySelector('.hero'),document.querySelector('.discovery'),document.querySelector('#insightSection')];
document.querySelectorAll('[data-view]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-link').forEach(n=>n.classList.remove('active'));btn.classList.add('active');const view=btn.dataset.view;discoverSections.forEach(s=>s.hidden=view!=='discover');neighborsView.hidden=view!=='neighbors';compareView.hidden=view!=='compare';if(view==='neighbors')loadNeighbors();if(view==='compare')loadSpotifyPlaylists();}));
const getImage=images=>(images||[]).slice().reverse().find(i=>i['#text'])?.['#text']||'';
const escapeHtml=value=>String(value||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const spotifyId=url=>{try{const u=new URL(url);const parts=u.pathname.split('/').filter(Boolean);return parts[0]==='user'&&parts[1]?parts[1]:''}catch{return ''}};
async function neighborDetails(name,match=''){const [info,top,recent]=await Promise.all([api.lastfm('user.getInfo',{user:name}),api.lastfm('user.getTopArtists',{user:name,period:'3month',limit:'4'}),api.lastfm('user.getRecentTracks',{user:name,limit:'1'})]);const user=info.user;const track=recent.recenttracks?.track?.[0];return{name:user.name,realname:user.realname,country:user.country,playcount:user.playcount,url:user.url,image:getImage(user.image),match,artists:(top.topartists?.artist||[]).map(a=>a.name),now:track?`${track.artist?.['#text']||track.artist?.name} — ${track.name}`:'Sin escucha reciente'};}
async function playlistsFor(name){const url=neighborStore[name]?.spotify||'';const id=spotifyId(url);if(!id)return[];try{const data=await api.spotify(`/users/${encodeURIComponent(id)}/playlists?limit=8`);return(data.items||[]).filter(Boolean).map(p=>({name:p.name,url:p.external_urls?.spotify}));}catch{return[]}}
async function renderNeighborCard(person){const playlists=await playlistsFor(person.name);const initials=person.name.slice(0,2).toUpperCase();const limit=neighborStore[person.name]?.limit??250;return `<article class="neighbor-card" data-neighbor="${escapeHtml(person.name)}"><button class="remove-neighbor" title="Quitar">×</button>${person.image?`<img class="neighbor-avatar" src="${escapeHtml(person.image)}" alt="">`:`<div class="neighbor-avatar">${initials}</div>`}<div class="neighbor-main"><h3>${escapeHtml(person.realname||person.name)}</h3><div class="neighbor-meta">@${escapeHtml(person.name)} · ${escapeHtml(person.country||'mundo')} · ${Number(person.playcount||0).toLocaleString()} scrobbles ${person.match?`· <span class="compatibility">${escapeHtml(person.match)} afinidad</span>`:''}</div><div class="neighbor-now">Escuchando: ${escapeHtml(person.now)}</div><div class="neighbor-artists">${person.artists.map(a=>`<span>${escapeHtml(a)}</span>`).join('')}</div><div class="neighbor-links"><a href="${escapeHtml(person.url)}" target="_blank">Last.fm ↗</a>${neighborStore[person.name]?.spotify?`<a href="${escapeHtml(neighborStore[person.name].spotify)}" target="_blank">Spotify ↗</a>`:`<button class="link-spotify">Vincular Spotify</button>`}<label class="neighbor-limit">Límite <input class="neighbor-limit-input" type="number" min="0" step="1" value="${limit}" title="0 significa sin límite"></label></div></div><div class="neighbor-playlists"><strong>PLAYLISTS PÚBLICAS</strong><div class="playlist-row">${playlists.length?playlists.map(p=>`<a class="playlist-chip" href="${escapeHtml(p.url)}" target="_blank">${escapeHtml(p.name)} ↗</a>`).join(''):'<span class="neighbor-meta">Vincula su perfil para verlas</span>'}</div></div></article>`;}
async function loadNeighbors(){if(!api){neighborsStatus.textContent='Instala la app para cargar tus vecinos.';return;}neighborsStatus.textContent='Buscando tus vecinos musicales…';let candidates=[];try{const result=await api.lastfm('user.getNeighbours',{limit:'12'});candidates=(result.neighbours?.user||[]).map(u=>({name:u.name,match:u.match||''}));}catch{}const manual=Object.entries(neighborStore).map(([name,v])=>({name,match:v.match||''}));candidates=[...candidates,...manual].filter((v,i,a)=>a.findIndex(x=>x.name.toLowerCase()===v.name.toLowerCase())===i).slice(0,12);currentNeighborNames=candidates.map(c=>c.name);if(!candidates.length){neighborsStatus.innerHTML='Last.fm no expuso la lista automática para esta cuenta. Añade un vecino con su usuario de Last.fm.';neighborsGrid.innerHTML='';return;}const details=(await Promise.all(candidates.map(c=>neighborDetails(c.name,c.match).catch(()=>null)))).filter(Boolean);neighborsStatus.textContent=`${details.length} vecinos encontrados`;neighborsGrid.innerHTML=(await Promise.all(details.map(renderNeighborCard))).join('');}
document.querySelector('#addNeighborBtn').addEventListener('click',()=>{neighborLastfm.value='';neighborSpotify.value='';neighborLimit.value='250';neighborDialog.showModal()});
document.querySelector('#neighborForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const name=neighborLastfm.value.trim();if(!name)return;neighborStore[name]={spotify:neighborSpotify.value.trim(),limit:Math.max(0,Number(neighborLimit.value)||0)};localStorage.setItem('recomendapp-neighbors',JSON.stringify(neighborStore));neighborDialog.close();loadNeighbors();});
document.querySelector('#neighborsGrid').addEventListener('click',e=>{const card=e.target.closest('.neighbor-card');if(!card)return;const name=card.dataset.neighbor;if(e.target.closest('.remove-neighbor')){delete neighborStore[name];localStorage.setItem('recomendapp-neighbors',JSON.stringify(neighborStore));loadNeighbors();}if(e.target.closest('.link-spotify')){const link=prompt(`Pega el enlace del perfil de Spotify de ${name}:`,'https://open.spotify.com/user/');if(link&&spotifyId(link)){neighborStore[name]={limit:250,...(neighborStore[name]||{}),spotify:link.trim()};localStorage.setItem('recomendapp-neighbors',JSON.stringify(neighborStore));loadNeighbors();}else if(link)notify('Ese enlace de Spotify no es válido');}if(e.target.closest('.limit-neighbor')){const current=neighborStore[name]?.limit??250;const value=prompt(`Máximo de scrobbles para ${name}. Usa 0 para no limitar:`,String(current));if(value!==null&&/^\d+$/.test(value.trim())){neighborStore[name]={...(neighborStore[name]||{}),limit:Number(value)};localStorage.setItem('recomendapp-neighbors',JSON.stringify(neighborStore));loadNeighbors();}else if(value!==null)notify('Introduce un número entero desde 0');}});
document.querySelector('#neighborsGrid').addEventListener('change',e=>{if(!e.target.matches('.neighbor-limit-input'))return;const name=e.target.closest('.neighbor-card').dataset.neighbor;const limit=Math.max(0,Math.floor(Number(e.target.value)||0));e.target.value=limit;neighborStore[name]={...(neighborStore[name]||{}),limit};localStorage.setItem('recomendapp-neighbors',JSON.stringify(neighborStore));notify(`Límite de ${name}: ${limit===0?'sin límite':limit}`);});
async function buildNeighborsPlaylist(){if(!currentNeighborNames.length){notify('Añade al menos un vecino primero');return;}const btn=document.querySelector('#syncPlaylistBtn');btn.disabled=true;btn.textContent='Buscando últimos scrobbles…';try{const feeds=await Promise.all(currentNeighborNames.map(name=>api.lastfm('user.getRecentTracks',{user:name,limit:'5'}).catch(()=>null)));const tracks=feeds.flatMap(f=>f?.recenttracks?.track||[]).map(t=>({name:t.name,artist:t.artist?.['#text']||t.artist?.name})).filter(t=>t.name&&t.artist).filter((t,i,a)=>a.findIndex(x=>`${x.artist}-${x.name}`.toLowerCase()===`${t.artist}-${t.name}`.toLowerCase())===i).slice(0,50);if(!tracks.length)throw new Error('No encontré scrobbles recientes públicos.');btn.textContent=`Buscando ${tracks.length} canciones en Spotify…`;const found=[];for(const track of tracks){const q=encodeURIComponent(`track:${track.name} artist:${track.artist}`);const result=await api.spotify(`/search?q=${q}&type=track&limit=1`);const uri=result.tracks?.items?.[0]?.uri;if(uri&&!found.includes(uri))found.push(uri);}if(!found.length)throw new Error('Spotify no encontró estas canciones.');let playlistId=localStorage.getItem('recomendapp-neighbors-playlist');let playlistUrl=localStorage.getItem('recomendapp-neighbors-playlist-url');if(!playlistId){const created=await api.spotify('/me/playlists',{method:'POST',body:{name:'Neighbors — Recomendapp',public:false,description:'Últimos scrobbles de mis vecinos musicales. Actualizada por Recomendapp.'}});playlistId=created.id;playlistUrl=created.external_urls?.spotify;localStorage.setItem('recomendapp-neighbors-playlist',playlistId);localStorage.setItem('recomendapp-neighbors-playlist-url',playlistUrl||'');}await api.spotify(`/playlists/${playlistId}/items`,{method:'PUT',body:{uris:found.slice(0,100)}});notify(`Playlist actualizada con ${found.length} canciones`);if(playlistUrl)window.open(playlistUrl,'_blank');}catch(e){if(/scope|permission|403/i.test(e.message)){notify('Spotify necesita un permiso nuevo. Autoriza de nuevo…');try{await api.connectSpotify();await buildNeighborsPlaylist();}catch(authError){notify(authError.message)}}else notify(e.message);}finally{btn.disabled=false;btn.textContent='♫ Actualizar playlist';}}
async function allScrobbles(name,from,max,onProgress){if(typeof max==='function'){onProgress=max;max=neighborStore[name]?.limit??250;}let page=1,totalPages=1,tracks=[];do{if(syncCancelled)throw new Error('__SYNC_CANCELLED__');const pageLimit=max>0?Math.min(200,Math.max(1,max-tracks.length)):200;const data=await api.lastfm('user.getRecentTracks',{user:name,from:String(from),limit:String(pageLimit),page:String(page)});const batch=data.recenttracks?.track||[];tracks.push(...batch);totalPages=Number(data.recenttracks?.['@attr']?.totalPages||1);const available=Number(data.recenttracks?.['@attr']?.total||tracks.length);if(onProgress)onProgress(name,tracks.length,max>0?Math.min(max,available):available);page++;}while(page<=totalPages&&(max===0||tracks.length<max));return tracks.slice(0,max||undefined).filter(t=>!t['@attr']?.nowplaying).map(t=>({name:t.name,artist:t.artist?.['#text']||t.artist?.name})).filter(t=>t.name&&t.artist);}
async function buildNeighborsPlaylist(){if(!currentNeighborNames.length){notify('Añade al menos un vecino primero');return;}const btn=document.querySelector('#syncPlaylistBtn');btn.disabled=true;btn.textContent='Leyendo scrobbles…';try{const days=Number(neighborPeriod.value);localStorage.setItem('recomendapp-neighbor-period',days);const from=Math.floor((Date.now()-days*86400000)/1000);const tracks=[];for(const name of currentNeighborNames){const userTracks=await allScrobbles(name,from,(user,loaded,total)=>btn.textContent=`${user}: ${loaded}/${total} scrobbles…`).catch(()=>[]);tracks.push(...userTracks);}if(!tracks.length)throw new Error('No encontré scrobbles públicos en ese periodo.');const unique=[...new Map(tracks.map(t=>[`${t.artist}\u0000${t.name}`.toLowerCase(),t])).values()];const uriMap=new Map(JSON.parse(localStorage.getItem('recomendapp-track-uri-cache')||'[]'));let searched=0;for(const track of unique){const key=`${track.artist}\u0000${track.name}`.toLowerCase();if(!uriMap.has(key)){btn.textContent=`Buscando en Spotify ${++searched}/${unique.length}…`;const q=encodeURIComponent(`track:${track.name} artist:${track.artist}`);const result=await api.spotify(`/search?q=${q}&type=track&limit=1`);uriMap.set(key,result.tracks?.items?.[0]?.uri||'');}}localStorage.setItem('recomendapp-track-uri-cache',JSON.stringify([...uriMap]));const found=tracks.map(t=>uriMap.get(`${t.artist}\u0000${t.name}`.toLowerCase())).filter(Boolean);if(!found.length)throw new Error('Spotify no encontró estas canciones.');let playlistId=localStorage.getItem('recomendapp-neighbors-playlist');let playlistUrl=localStorage.getItem('recomendapp-neighbors-playlist-url');if(!playlistId){const created=await api.spotify('/me/playlists',{method:'POST',body:{name:'Neighbors — Recomendapp',public:false,description:'Todos los scrobbles del periodo seleccionado para mis vecinos. Actualizada por Recomendapp.'}});playlistId=created.id;playlistUrl=created.external_urls?.spotify;localStorage.setItem('recomendapp-neighbors-playlist',playlistId);localStorage.setItem('recomendapp-neighbors-playlist-url',playlistUrl||'');}btn.textContent=`Guardando ${found.length} scrobbles…`;await api.spotify(`/playlists/${playlistId}/items`,{method:'PUT',body:{uris:found.slice(0,100)}});for(let i=100;i<found.length;i+=100){btn.textContent=`Guardando ${Math.min(i+100,found.length)}/${found.length}…`;await api.spotify(`/playlists/${playlistId}/items`,{method:'POST',body:{uris:found.slice(i,i+100)}});}const missing=tracks.length-found.length;notify(`Playlist: ${found.length}/${tracks.length} scrobbles${missing?` · ${missing} no encontrados`:''}`);if(playlistUrl)window.open(playlistUrl,'_blank');}catch(e){if(/scope|permission|403/i.test(e.message)){notify('Spotify necesita permisos nuevos. Autoriza de nuevo…');try{await api.connectSpotify();await buildNeighborsPlaylist();}catch(authError){notify(authError.message)}}else notify(e.message);}finally{btn.disabled=false;btn.textContent='♫ Actualizar playlist';}}
async function spotifyUrisFast(tracks,btn){
  const unique=[...new Map(tracks.map(t=>[`${t.artist}\u0000${t.name}`.toLowerCase(),t])).values()];
  const uriMap=new Map(JSON.parse(localStorage.getItem('recomendapp-track-uri-cache')||'[]'));
  const pending=unique.filter(t=>!uriMap.has(`${t.artist}\u0000${t.name}`.toLowerCase()));
  let cursor=0,completed=0;
  const persist=()=>localStorage.setItem('recomendapp-track-uri-cache',JSON.stringify([...uriMap]));
  async function worker(){while(cursor<pending.length){if(syncCancelled)return;const track=pending[cursor++];syncCurrent.textContent=`Buscando: ${track.artist} — ${track.name}`;const key=`${track.artist}\u0000${track.name}`.toLowerCase();const q=encodeURIComponent(`track:${track.name} artist:${track.artist}`);const result=await api.spotify(`/search?q=${q}&type=track&limit=1`);uriMap.set(key,result.tracks?.items?.[0]?.uri||'');completed++;btn.textContent=`Spotify: ${completed}/${pending.length}`;syncStage.textContent='Buscando canciones en Spotify';syncNumbers.textContent=`${completed} / ${pending.length}`;syncBar.style.width=`${pending.length?completed/pending.length*100:100}%`;if(completed%20===0)persist();}}
  if(pending.length)await Promise.all(Array.from({length:Math.min(10,pending.length)},worker));
  persist();
  if(syncCancelled)throw new Error('__SYNC_CANCELLED__');
  return {uris:tracks.map(t=>uriMap.get(`${t.artist}\u0000${t.name}`.toLowerCase())).filter(Boolean),cached:unique.length-pending.length,searched:pending.length};
}
async function buildNeighborsPlaylistFast(){
  if(!currentNeighborNames.length){notify('Añade al menos un vecino primero');return;}
  const btn=document.querySelector('#syncPlaylistBtn');syncCancelled=false;cancelSyncBtn.disabled=false;btn.disabled=true;btn.textContent='Leyendo scrobbles…';syncProgress.hidden=false;syncStage.textContent='Leyendo Last.fm';syncNumbers.textContent='';syncBar.style.width='0%';syncCurrent.textContent='Recopilando scrobbles de tus neighbors…';
  try{
    const days=Number(neighborPeriod.value);localStorage.setItem('recomendapp-neighbor-period',days);const from=Math.floor((Date.now()-days*86400000)/1000);const tracks=[];
    for(const name of currentNeighborNames){const limit=neighborStore[name]?.limit??250;const userTracks=await allScrobbles(name,from,limit,(user,loaded,total)=>btn.textContent=`${user}: ${loaded}/${total} scrobbles…`).catch(error=>{if(error.message==='__SYNC_CANCELLED__')throw error;return[]});tracks.push(...userTracks);}
    if(!tracks.length)throw new Error('No encontré scrobbles públicos en ese periodo.');
    const resolved=await spotifyUrisFast(tracks,btn);const found=resolved.uris;if(!found.length)throw new Error('Spotify no encontró estas canciones.');
    let playlistId=localStorage.getItem('recomendapp-neighbors-playlist');let playlistUrl=localStorage.getItem('recomendapp-neighbors-playlist-url');
    if(!playlistId){const created=await api.spotify('/me/playlists',{method:'POST',body:{name:'Neighbors — Recomendapp',public:false,description:'Scrobbles de mis vecinos con límites personalizados. Actualizada por Recomendapp.'}});playlistId=created.id;playlistUrl=created.external_urls?.spotify;localStorage.setItem('recomendapp-neighbors-playlist',playlistId);localStorage.setItem('recomendapp-neighbors-playlist-url',playlistUrl||'');}
    btn.textContent=`Guardando ${found.length} scrobbles…`;await api.spotify(`/playlists/${playlistId}/items`,{method:'PUT',body:{uris:found.slice(0,100)}});
    for(let i=100;i<found.length;i+=100){btn.textContent=`Guardando ${Math.min(i+100,found.length)}/${found.length}…`;await api.spotify(`/playlists/${playlistId}/items`,{method:'POST',body:{uris:found.slice(i,i+100)}});}
    notify(`${found.length}/${tracks.length} scrobbles · ${resolved.cached} coincidencias desde caché`);if(playlistUrl)window.open(playlistUrl,'_blank');
  }catch(e){if(e.message==='__SYNC_CANCELLED__'){syncStage.textContent='Búsqueda detenida';syncCurrent.textContent='El progreso encontrado quedó guardado para la próxima vez.';notify('Búsqueda detenida')}else if(/scope|permission|403/i.test(e.message)){notify('Spotify necesita permisos. Autoriza de nuevo…');try{await api.connectSpotify();await buildNeighborsPlaylistFast();}catch(authError){notify(authError.message)}}else notify(e.message);}finally{btn.disabled=false;cancelSyncBtn.disabled=true;btn.textContent='♫ Actualizar playlist';if(!syncCancelled){syncStage.textContent='Proceso finalizado';syncBar.style.width='100%';}}
}
document.querySelector('#syncPlaylistBtn').addEventListener('click',buildNeighborsPlaylistFast);
document.querySelector('#cancelSyncBtn').addEventListener('click',()=>{syncCancelled=true;cancelSyncBtn.disabled=true;syncStage.textContent='Deteniendo…';syncCurrent.textContent='Esperando que terminen las búsquedas actualmente en curso.';});
neighborPeriod.value=localStorage.getItem('recomendapp-neighbor-period')||'7';
async function loadSpotifyPlaylists(){if(!api)return;sourcePlaylist.innerHTML=referencePlaylist.innerHTML='<option>Cargando…</option>';try{let items=[],offset=0,data;do{data=await api.spotify(`/me/playlists?limit=50&offset=${offset}`);items.push(...(data.items||[]).filter(Boolean));offset+=50;}while(data.next&&offset<500);const options=items.map(p=>`<option value="${p.id}">${escapeHtml(p.name)} (${p.items?.total??p.tracks?.total??0})</option>`).join('');sourcePlaylist.innerHTML=options;referencePlaylist.innerHTML=options;if(items.length>1)referencePlaylist.selectedIndex=1;}catch(e){if(/scope|permission|403/i.test(e.message)){notify('Autoriza Spotify para leer tus playlists');await api.connectSpotify();return loadSpotifyPlaylists();}notify(e.message)}}
async function playlistItems(id,onProgress){let items=[],offset=0,data;do{data=await api.spotify(`/playlists/${id}/items?limit=50&offset=${offset}`);items.push(...(data.items||[]));offset+=data.limit||50;if(onProgress)onProgress(items.length,data.total||items.length);}while(data.next);return items.map(row=>row.item||row.track).filter(t=>t?.type==='track'&&t.uri).map(t=>({uri:t.uri,name:t.name,artist:(t.artists||[]).map(a=>a.name).join(', '),artistIds:(t.artists||[]).map(a=>a.id)}));}
document.querySelectorAll('.mode-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.mode-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');compareMode=btn.dataset.mode;}));
document.querySelector('#compareBtn').addEventListener('click',async()=>{if(sourcePlaylist.value===referencePlaylist.value){notify('Selecciona dos playlists diferentes');return;}compareBtn.disabled=true;compareBtn.textContent='Leyendo playlists…';try{let sourceProgress='0',referenceProgress='0';const updateProgress=()=>compareBtn.textContent=`Cargando ${sourceProgress} + ${referenceProgress} canciones…`;const [source,reference]=await Promise.all([playlistItems(sourcePlaylist.value,(loaded,total)=>{sourceProgress=`${loaded}/${total}`;updateProgress()}),playlistItems(referencePlaylist.value,(loaded,total)=>{referenceProgress=`${loaded}/${total}`;updateProgress()})]);compareBtn.textContent='Calculando diferencia…';const known=new Set(reference.flatMap(t=>compareMode==='artist'?t.artistIds:[t.uri]));compareTracks=source.filter(t=>compareMode==='artist'?t.artistIds.length&&t.artistIds.every(id=>!known.has(id)):!known.has(t.uri));resultTitle.textContent=`${compareTracks.length} canciones nuevas`;resultTracks.innerHTML=`<div class="neighbor-meta">Analizadas ${source.length.toLocaleString()} canciones fuente contra ${reference.length.toLocaleString()} de referencia · filtro por ${compareMode==='artist'?'artistas':'canciones'}</div>`+(compareTracks.length?compareTracks.map((t,i)=>`<div class="result-track"><span>${String(i+1).padStart(2,'0')}</span><strong>${escapeHtml(t.name)}</strong><span>${escapeHtml(t.artist)}</span></div>`).join(''):'<div class="neighbors-status">No hay elementos nuevos con este filtro.</div>');compareResult.hidden=false;}catch(e){notify(e.message)}finally{compareBtn.disabled=false;compareBtn.textContent='Comparar playlists →'}});
document.querySelector('#saveCompareBtn').addEventListener('click',async()=>{if(!compareTracks.length)return;saveCompareBtn.disabled=true;try{const sourceName=sourcePlaylist.options[sourcePlaylist.selectedIndex].text.replace(/ \(\d+\)$/,'');const created=await api.spotify('/me/playlists',{method:'POST',body:{name:`${sourceName} — solo nuevo`,public:false,description:`Resultado de Compare por ${compareMode==='artist'?'artistas':'canciones'} en Recomendapp.`}});for(let i=0;i<compareTracks.length;i+=100)await api.spotify(`/playlists/${created.id}/items`,{method:'POST',body:{uris:compareTracks.slice(i,i+100).map(t=>t.uri)}});notify('Playlist nueva creada en Spotify');window.open(created.external_urls.spotify,'_blank');}catch(e){notify(e.message)}finally{saveCompareBtn.disabled=false}});
render();
loadConfig();
